In [7]:
import numpy as np
import pandas as pd

$$
p_{i}' = \frac{\sum_{j} w_{ij} \frac{p_j}{p_i + p_j}}{\sum_{j} \frac{w_{ji}}{p_i + p_j}}
$$


In [24]:
def PL_MLE(df, p=None, max_iter=10):
    """
    A function that takes a dataframe of competition between items as input and
    returns their estimated worth (numeric) using immediate Plackett-Luce Model.
    """
    import numpy as np

    # Initialize worth values to 1 if not provided
    if p is None:
        p = np.ones(len(df)) 
    labels = df.columns
    
    for iteration in range(max_iter):
        # Perform updates
        for i in range(len(p)):
            numerator = 0.0
            denominator = 0.0

            for j in range(len(p)):
                if i != j:
                    w_ij = df.iloc[i, j]
                    w_ji = df.iloc[j, i]
                    numerator += w_ij * p[j] / (p[i] + p[j])
                    denominator += w_ji / (p[i] + p[j])

            # Avoid zero division
            p[i] = numerator / denominator if denominator != 0 else 0.0

        # Normalize p to keep numerical stability
        norm = np.prod(p) ** (1 / len(p))
        p = p / norm

        result_dict = {label: float(value) for label, value in zip(labels, p)}
        print(f"Iteration {iteration + 1}: {result_dict}")

    return result_dict

In [25]:
data = {
    'A': [0, 1, 2],
    'B': [2, 0, 1],
    'C': [1, 2, 0]
}
df = pd.DataFrame(data, index=['A', 'B', 'C'])
df

A  B  C
A  0  2  1
B  1  0  2
C  2  1  0

In [26]:
PL_MLE(df)

Iteration 1: {'A': 1.0, 'B': 1.0, 'C': 1.0}
Iteration 2: {'A': 1.0, 'B': 1.0, 'C': 1.0}
Iteration 3: {'A': 1.0, 'B': 1.0, 'C': 1.0}
Iteration 4: {'A': 1.0, 'B': 1.0, 'C': 1.0}
Iteration 5: {'A': 1.0, 'B': 1.0, 'C': 1.0}
Iteration 6: {'A': 1.0, 'B': 1.0, 'C': 1.0}
Iteration 7: {'A': 1.0, 'B': 1.0, 'C': 1.0}
Iteration 8: {'A': 1.0, 'B': 1.0, 'C': 1.0}
Iteration 9: {'A': 1.0, 'B': 1.0, 'C': 1.0}
Iteration 10: {'A': 1.0, 'B': 1.0, 'C': 1.0}


{'A': 1.0, 'B': 1.0, 'C': 1.0}

In [30]:
data = { "A" : [0, 1, 2,2,2], "B": [2, 0, 2,3,3], 
    "C": [1,1,0, 2, 2],  "D" : [1, 0, 1,0,3], "E": [1, 0, 1,0,0]
}
df = pd.DataFrame(data, index=['A', 'B', 'C',"D",'E'])
df

A  B  C  D  E
A  0  2  1  1  1
B  1  0  1  0  0
C  2  2  0  1  1
D  2  3  2  0  0
E  2  3  2  3  0

In [31]:
PL_MLE(df)

Iteration 1: {'A': 1.0215406165266616, 'B': 0.2537375079759772, 'C': 0.8893892032147656, 'D': 1.0870931312060157, 'E': 3.990259003624429}
Iteration 2: {'A': 0.7442295641369935, 'B': 0.24018177644237548, 'C': 0.9688967953105313, 'D': 1.4274017244287847, 'E': 4.045100281934719}
Iteration 3: {'A': 0.7249613307432117, 'B': 0.24924076458809055, 'C': 1.0081623227202936, 'D': 1.3680840212726442, 'E': 4.012572105794215}
Iteration 4: {'A': 0.7281713458837457, 'B': 0.24947200320578256, 'C': 0.999113583941843, 'D': 1.3735575939156768, 'E': 4.011278932264707}
Iteration 5: {'A': 0.7283869200602663, 'B': 0.24923762344939152, 'C': 1.000076303378184, 'D': 1.3729459483116022, 'E': 4.011785307245589}
Iteration 6: {'A': 0.7283097841194621, 'B': 0.2492711910896233, 'C': 0.9999907464486988, 'D': 1.3730403338326704, 'E': 4.011737337789709}
Iteration 7: {'A': 0.7283182120255759, 'B': 0.24926817389946995, 'C': 1.0000015731323735, 'D': 1.3730254092633254, 'E': 4.011739646042707}
Iteration 8: {'A': 0.7283176002

{'A': 0.7283176528861063,
 'B': 0.24926843001210564,
 'C': 0.9999999956268865,
 'D': 1.3730272729292998,
 'E': 4.011739487251034}

## Using Pytorch and Gradient Ascent

In [40]:
import torch

#empty tensor
x = torch.empty(4)
print(x)
y = torch.rand([2,3], )
print(y)
z =  torch.ones([1,2], dtype = torch.int)
print(z.dtype)

tensor([2.3694e-38, 3.6013e-43, 0.0000e+00, 0.0000e+00])
tensor([[0.6317, 0.7130, 0.8553],
        [0.3997, 0.3693, 0.3877]])
torch.int32


In [41]:
x.size()

torch.Size([4])

In [42]:
torch.tensor([2,3,4])


tensor([2, 3, 4])

In [44]:
y+y

tensor([[1.2635, 1.4260, 1.7106],
        [0.7994, 0.7387, 0.7754]])

In [47]:
torch.add(y,y)

tensor([[1.2635, 1.4260, 1.7106],
        [0.7994, 0.7387, 0.7754]])

In [50]:
y.add_(y)

tensor([[1.2635, 1.4260, 1.7106],
        [0.7994, 0.7387, 0.7754]])

In [52]:
x = torch.rand(4,4)
#resizing
b=  x.view(-1, 8)
c =  x.view(16)
b

tensor([[0.1800, 0.4595, 0.0341, 0.2344, 0.2143, 0.8378, 0.2954, 0.2335],
        [0.9140, 0.7630, 0.0517, 0.0631, 0.3332, 0.7562, 0.1266, 0.2767]])

In [55]:
n = torch.ones(5)
m = n.numpy()
print(m)
type(m)

[1. 1. 1. 1. 1.]


numpy.ndarray

In [58]:
n.add_(1)   #they are both changing because of memory location

tensor([2., 2., 2., 2., 2.])

In [59]:
m

array([2., 2., 2., 2., 2.], dtype=float32)

In [61]:
nump = np.ones(5)
toch = torch.from_numpy(nump)
toch

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [63]:
x = torch.ones(5, requires_grad = True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [85]:
## Autograd

x = torch.randn(3, requires_grad = True)
x

tensor([0.4997, 1.4350, 1.4263], requires_grad=True)

In [86]:
y = x+2
y

tensor([2.4997, 3.4350, 3.4263], grad_fn=<AddBackward0>)

In [91]:
z = y*y*2
#z = z.mean()
z

tensor([12.4973, 23.5984, 23.4797], grad_fn=<MulBackward0>)

In [93]:
z.backward()  #dz/dx
print(x.grad)

tensor([3.3330, 4.5800, 4.5685])


In [95]:
#how to remove the require gradient
#x.requires_grad_(False)
#x.detach()
#with_torch.no_grad():
x.requires_grad_(False)
x

tensor([0.4997, 1.4350, 1.4263])

In [97]:
y = x.detach()
y =  x+2
y

tensor([2.4997, 3.4350, 3.4263])

In [108]:
weights = torch.ones(4, requires_grad = True)
for epoch in range(3):
    model_output =  (weights*3).sum()
    model_output.backward()
    print(weights.grad) \
    #before next iteration, you must empty the grad
    weights.grad.zero_() #without this it will be accumulatiing

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [111]:
#optimizer = torch.optim.SGD(weights, lr = 0.01)
#optimizer.step()
#optimizer.zero_grad()

In [115]:
### Backpropagation

x = torch.tensor(1.0)
y = torch.tensor(2.0)

w = torch.tensor(1.0, requires_grad = True)
#forward pass

y_hat =  w*x
loss = (y_hat -y)**2
loss
#backward pass
loss.backward()
w.grad
#update weight
###next forward and backward for some iteration

tensor(-2.)

In [118]:
df

A  B  C  D  E
A  0  2  1  1  1
B  1  0  1  0  0
C  2  2  0  1  1
D  2  3  2  0  0
E  2  3  2  3  0

In [119]:
PL_MLE(df)

Iteration 1: {'A': 1.0215406165266616, 'B': 0.2537375079759772, 'C': 0.8893892032147656, 'D': 1.0870931312060157, 'E': 3.990259003624429}
Iteration 2: {'A': 0.7442295641369935, 'B': 0.24018177644237548, 'C': 0.9688967953105313, 'D': 1.4274017244287847, 'E': 4.045100281934719}
Iteration 3: {'A': 0.7249613307432117, 'B': 0.24924076458809055, 'C': 1.0081623227202936, 'D': 1.3680840212726442, 'E': 4.012572105794215}
Iteration 4: {'A': 0.7281713458837457, 'B': 0.24947200320578256, 'C': 0.999113583941843, 'D': 1.3735575939156768, 'E': 4.011278932264707}
Iteration 5: {'A': 0.7283869200602663, 'B': 0.24923762344939152, 'C': 1.000076303378184, 'D': 1.3729459483116022, 'E': 4.011785307245589}
Iteration 6: {'A': 0.7283097841194621, 'B': 0.2492711910896233, 'C': 0.9999907464486988, 'D': 1.3730403338326704, 'E': 4.011737337789709}
Iteration 7: {'A': 0.7283182120255759, 'B': 0.24926817389946995, 'C': 1.0000015731323735, 'D': 1.3730254092633254, 'E': 4.011739646042707}
Iteration 8: {'A': 0.7283176002

{'A': 0.7283176528861063,
 'B': 0.24926843001210564,
 'C': 0.9999999956268865,
 'D': 1.3730272729292998,
 'E': 4.011739487251034}

In [132]:
plackett_luce_torch(df, lr=0.07, max_iter=100)

Iteration 1: p = [0.93182908 0.93182908 1.00196675 1.07210442 1.07210442]
Iteration 10: p = [0.753838   0.41186676 0.99111579 1.66856514 1.94759058]
Iteration 20: p = [0.80485716 0.19565557 0.99305176 1.94051966 3.29533106]
Iteration 30: p = [0.70754567 0.30722205 1.02985761 1.31475204 3.39759888]
Iteration 40: p = [0.82072326 0.23458286 1.00937849 1.3137588  3.91685327]
Iteration 50: p = [0.66336754 0.2529158  0.97895317 1.44573008 4.21134375]
Iteration 60: p = [0.76083241 0.24452414 1.00658226 1.32158181 4.04060069]
Iteration 70: p = [0.71283668 0.25300537 1.00275751 1.37707522 4.01537989]
Iteration 80: p = [0.73240252 0.24629335 1.00165981 1.3847457  3.99675214]
Iteration 90: p = [0.73054349 0.25169045 0.9996319  1.36644506 3.98157507]
Iteration 100: p = [0.72604468 0.2486387  0.9985889  1.38042063 4.01855352]


{'A': 0.7260446816350722,
 'B': 0.24863869780215955,
 'C': 0.9985888951779122,
 'D': 1.3804206281045812,
 'E': 4.018553515504488}

In [133]:
data = {
    'A': [0, 3, 2],
    'B': [1, 0, 4],
    'C': [2, 3, 0]
}
df = pd.DataFrame(data, index=['A', 'B', 'C'])

result = plackett_luce_torch(df)
print("Final estimates:", result)


Iteration 1: p = [0.98675472 1.00668916 1.00668916]
Iteration 10: p = [0.87515644 1.06894942 1.06894942]
Iteration 20: p = [0.7739861  1.13666744 1.13666744]
Iteration 30: p = [0.70886755 1.18772925 1.18772925]
Iteration 40: p = [0.68624774 1.20714527 1.20714527]
Iteration 50: p = [0.69401301 1.20037293 1.20037293]
Iteration 60: p = [0.70917939 1.18746808 1.18746808]
Iteration 70: p = [0.71652406 1.18136639 1.18136639]
Iteration 80: p = [0.71513978 1.18250921 1.18250921]
Iteration 90: p = [0.71146788 1.18555676 1.18555676]
Iteration 100: p = [0.71005742 1.18673367 1.18673367]
Final estimates: {'A': 0.710057418207784, 'B': 1.186733673163536, 'C': 1.186733673163536}


In [134]:
PL_MLE(df)

Iteration 1: {'A': 0.7113786608980126, 'B': 1.1856311014966876, 'C': 1.1856311014966876}
Iteration 2: {'A': 0.7113786608980125, 'B': 1.1856311014966876, 'C': 1.1856311014966876}
Iteration 3: {'A': 0.7113786608980127, 'B': 1.1856311014966876, 'C': 1.1856311014966876}
Iteration 4: {'A': 0.7113786608980125, 'B': 1.1856311014966876, 'C': 1.1856311014966876}
Iteration 5: {'A': 0.7113786608980127, 'B': 1.1856311014966876, 'C': 1.1856311014966876}
Iteration 6: {'A': 0.7113786608980125, 'B': 1.1856311014966876, 'C': 1.1856311014966876}
Iteration 7: {'A': 0.7113786608980127, 'B': 1.1856311014966876, 'C': 1.1856311014966876}
Iteration 8: {'A': 0.7113786608980125, 'B': 1.1856311014966876, 'C': 1.1856311014966876}
Iteration 9: {'A': 0.7113786608980127, 'B': 1.1856311014966876, 'C': 1.1856311014966876}
Iteration 10: {'A': 0.7113786608980125, 'B': 1.1856311014966876, 'C': 1.1856311014966876}


{'A': 0.7113786608980125, 'B': 1.1856311014966876, 'C': 1.1856311014966876}